version: '3.8'

services:
  app:
    build: .
    container_name: restaurante-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/restaurante
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - restaurante-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: restaurante-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=restaurante
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - restaurante-network
    restart: unless-stopped

networks:
  restaurante-network:
    driver: bridge

volumes:
  postgres_data: