spring:
  application:
    name: restaurante-api

  # Configuração de perfis
  profiles:
    active: dev

  # Configuração do JPA (comum para todos os ambientes)
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  # Configuração do Flyway (comum para todos os ambientes)
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# Configurações de segurança e JWT
app:
  security:
    jwt:
      secret-key: ${JWT_SECRET:chaveSecretaTemporariaParaDesenvolvimentoDeveSerAlteradaEmProducao}
      expiration-ms: 86400000 # 24 horas
      refresh-token-expiration-ms: 604800000 # 7 dias

# Configuração do servidor
server:
  port: 8080
  servlet:
    context-path: /api/v1

# Configuração do Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true

# Configuração de log (comum para todos os ambientes)
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO