spring:
  # Configuração do banco de dados PostgreSQL para produção
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:restaurante}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      # Configurações de pool de conexões
      connection-timeout: 30000     # 30 segundos de timeout
      minimum-idle: 5               # mínimo de conexões ociosas
      maximum-pool-size: 20         # máximo de conexões no pool
      idle-timeout: 600000          # 10 minutos de timeout para conexões ociosas
      max-lifetime: 1800000         # máximo de 30 minutos para uma conexão
      auto-commit: true

  # Configuração JPA específica para produção
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate  # Nunca use 'create' ou 'update' em produção
    properties:
      hibernate:
        format_sql: false

  # Configuração Flyway para produção
  flyway:
    clean-disabled: true  # Impede a limpeza acidental do banco em produção
    baseline-on-migrate: true

# Configurações específicas de segurança para produção
app:
  security:
    jwt:
      secret-key: ${JWT_SECRET}  # Deve ser definido via variável de ambiente
      expiration-ms: ${JWT_EXPIRATION:86400000}

# Configurações de servidor para produção
server:
  error:
    include-stacktrace: never
    include-message: never
  tomcat:
    max-threads: 200
    min-spare-threads: 20
    max-connections: 10000
    connection-timeout: 5000

# Configuração de log para produção
logging:
  level:
    root: WARN
    com.restaurante: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
  file:
    name: /var/log/restaurante-api/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Desabilitar API Docs em produção (opcional, dependendo dos requisitos)
# springdoc:
#   api-docs:
#     enabled: false
#   swagger-ui:
#     enabled: false