spring:
  application:
    name: restaurante-api

  # Configuração de perfis
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:restaurantedb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
    enabled: true
    path: /h2-console
    settings:
    web-allow-others: false

  # Configuração do JPA (comum para todos os ambientes)
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true



# Configurações de segurança e JWT
app:
  security:
    jwt:
      secret-key: "zVr7ZKQFOyC2vXKPN7M7f8m5vnW91tNKUn3J1Uc7q3Y="
      expiration-ms: 86400000 # 24 horas
      refresh-token-expiration-ms: 604800000 # 7 dias

# Configuração do servidor
server:
  port: 8080
  servlet:
    context-path: /

# Configuração do Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true

# Configuração de log (comum para todos os ambientes)
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO